# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Build and Test

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: install pyenv
    steps:
    - name: setup pyenv
      uses: "gabrielfalcao/pyenv-action@v18"
      with:
        default: 3.10.16
        #versions: 3.8.16, 3.5.7
    - name: Create virtualenv for python 3.10
      run: pyenv local 3.10.16 && python3 -mvenv .venv31016
    - name: Verify Python Versions
      run: |
        source $GITHUB_ENV
        python --version
        pyenv versions
    - name: Install dependencies
      run: |
        # python -m pip install --upgrade pip
        pip install hatch
    - name: Cache Hatch
      id: cache-hatch
      uses: actions/cache@v3
      with:
        path: /home/runner/.local/share/hatch/env/virtual/
        key: ${{ runner.os }}-hatch
    - name: Build
      run: hatch build
     # Install Minikube
    - name: Install Minikube
      run: |
        sudo apt-get update -y
        sudo apt-get install -y apt-transport-https
        sudo curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        sudo install minikube-linux-amd64 /usr/local/bin/minikube
    # Start Minikube
    - name: Start Minikube
      run: |
        minikube start --driver=docker
    # Set and export KUBECONFIG path
    - name: Set KUBECONFIG path
      run: |
        cp ~/.kube/config ~/.kube/kubeconfig-t2-dev.yaml
        echo "KUBECONFIG=$HOME/.kube/config" >> $GITHUB_ENV
    - name: Run Tests with Hatch
      run: |
        source $GITHUB_ENV
        export HATCH_PYTHON_PATH=$(which python3)
        #hatch run test.py310:cov
        hatch -e test run nose2 --verbose

