# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Build and Test

on:
  push:
    branches: [ "ESAEOEPCA-184" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: "pip"
    - name: Install dependencies
      run: |
        # python -m pip install --upgrade pip
        pip install hatch
    - name: Cache Hatch
      id: cache-hatch
      uses: actions/cache@v3
      with:
        path: /home/runner/.local/share/hatch/env/virtual/
        key: ${{ runner.os }}-hatch
    - name: Build
      run: hatch build
     # Install Minikube
    - name: Install Minikube
      run: |
        apt-get update -y
        apt-get install -y apt-transport-https
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        install minikube-linux-amd64 /usr/local/bin/minikube
    # Start Minikube
    - name: Start Minikube
      run: |
        minikube start --driver=docker
    # Set and export KUBECONFIG path
    - name: Set KUBECONFIG path
      run: |
        cp ~/.kube/config ~/.kube/kubeconfig-t2-dev.yaml
        echo "KUBECONFIG=$HOME/.kube/config" >> $GITHUB_ENV
    - name: Test package
      run: hatch -e test run nose2 --verbose
