# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Build and Test

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    name: install pyenv
    steps:
    - uses: actions/checkout@v4
    # - name: setup pyenv
    #   uses: "gabrielfalcao/pyenv-action@v18"
    #   with:
    #     default: 3.10.13
    #     #versions: 3.8.16, 3.5.7
    # - name: Create virtualenv for python 3.10
    #   run: pyenv install --list && pyenv local 3.10.13 && python3 -mvenv .venv31013
    # - name: Verify Python Versions
    #   run: |
    #     source $GITHUB_ENV
    #     python --version
    #     pyenv versions
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        # python -m pip install --upgrade pip
        sudo apt-get update -qy
        sudo apt-get install -y pipx
        pipx install hatch
    - name: Cache Hatch
      id: cache-hatch
      uses: actions/cache@v3
      with:
        path: /home/runner/.local/share/hatch/env/virtual/
        key: ${{ runner.os }}-hatch
    - name: Build
      run: hatch build
     # Install Minikube
    - name: Install Minikube
      run: |
        sudo apt-get install -y apt-transport-https
        sudo curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        sudo install minikube-linux-amd64 /usr/local/bin/minikube
    # Start Minikube
    - name: Start Minikube
      run: |
        minikube start --driver=docker
    # Set and export KUBECONFIG path
    - name: Set Envs and paths
      run: |
        cp ~/.kube/config ~/.kube/kubeconfig-t2-dev.yaml
        echo "KUBECONFIG=$HOME/.kube/config" >> $GITHUB_ENV
        py3_path=$(which python3)
        echo "HATCH_PYTHON_PATH=$py3_path" >> $GITHUB_ENV
    - name: Run Tests with Hatch
      run: |
        #hatch run test.py310:cov
        hatch -e test run +py=${{ matrix.python-version }} nose2

