name: docs
on:
  push:
    branches:
      - develop
      - main
    paths:
      # Only rebuild website when docs have changed
      - 'README.md'
      - 'docs/**'
      - 'mkdocs.yml'
      - .github/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Conda environment from environment.yml
        uses: mamba-org/provision-with-micromamba@main
        with:
            environment-file: docs/environment.yml
            environment-name: env_zoo_calrissian
            channels: terradue,eoepca,conda-forge
            channel-priority: flexible

      - name: Install project
        run: |
          /home/runner/micromamba-root/envs/env_zoo_calrissian/bin/python setup.py install
      - name: update API docs
        run: |
          /home/runner/micromamba-root/envs/env_zoo_calrissian/bin/pdocs as_markdown --output_dir docs/api/ --exclude_source --overwrite zoo_calrissian_runner

      - run: /home/runner/micromamba-root/envs/env_zoo_calrissian/bin/mkdocs gh-deploy --force
